version: '3'
services:
  backend:
    image: my-backend-image
    ports:
      - "8080:8080"
    networks:
      - my-network
  frontend:
    image: my-frontend-image
    ports:
      - "80:80"
    networks:
      - my-network
networks:
  my-network:

